### ISSUE TITLE
Simplify range(0, x) to range(x) in all Python files

### ISSUE THREAD

**Issue by dongskyler** [BadwaterBay/intelli-trip-planner#192]
## Background

In Python, `range(0, x)` is equivalent to `range(x)`, with `x` being an integer.

## Task

Replace all `range(0, x)` instances with `range(x)` in all files in this repo.

At least, the following file contains `range(0, x)`:

- [`src/core/distancematrix/google_distance_matrix.py`](https://github.com/BadwaterBay/intelli-trip-planner/blob/main/src/core/distancematrix/google_distance_matrix.py):
    - On [Line 34](https://github.com/BadwaterBay/intelli-trip-planner/blob/9376d32f36bb2f509fec70df9ecba2b7f55915f3/src/core/distancematrix/google_distance_matrix.py#L34)
    - On [Line 36](https://github.com/BadwaterBay/intelli-trip-planner/blob/9376d32f36bb2f509fec70df9ecba2b7f55915f3/src/core/distancematrix/google_distance_matrix.py#L36)

Please check if any other file contains `range(0, x)` instances.

Please refer to [contributing guidelines](https://github.com/BadwaterBay/intelli-trip-planner/blob/main/CONTRIBUTING.md) for environment setup and workflow.

Should you have any questions, please don't hesitate to comment under this issue.

## Impact

Completing this issue will simplify our code.

**Comment by wei200** [comment]
Claim to solve it.

**Comment by dongskyler** [comment]
> Claim to solve it.

Bravo
